export type Word = {
  en: string;
  ko: string;
  example: string;
};

export const WORDS: Word[] = [
  { en: "accommodate", ko: "수용하다, 숙박시키다", example: "The hotel can accommodate up to 500 guests." },
  { en: "acquire", ko: "인수하다, 획득하다", example: "The firm plans to acquire a smaller competitor." },
  { en: "allocate", ko: "할당하다", example: "We need to allocate more funds to marketing." },
  { en: "anticipate", ko: "예상하다", example: "We anticipate strong sales this quarter." },
  { en: "applicant", ko: "지원자", example: "Each applicant must submit a résumé." },
  { en: "approve", ko: "승인하다", example: "The manager approved the budget request." },
  { en: "attend", ko: "참석하다", example: "All staff must attend the safety training." },
  { en: "audit", ko: "회계 감사", example: "The annual audit will begin next week." },
  { en: "available", ko: "이용 가능한", example: "The report is available on our website." },
  { en: "brochure", ko: "안내 책자", example: "Please take a brochure at the front desk." },
  { en: "budget", ko: "예산", example: "The project was completed under budget." },
  { en: "candidate", ko: "후보자", example: "She is the strongest candidate for the job." },
  { en: "colleague", ko: "동료", example: "I discussed the idea with a colleague." },
  { en: "commute", ko: "통근하다", example: "He commutes to work by subway." },
  { en: "compensation", ko: "보상, 급여", example: "The compensation package includes health insurance." },
  { en: "competitive", ko: "경쟁력 있는", example: "We offer competitive prices." },
  { en: "complimentary", ko: "무료의", example: "Guests receive a complimentary breakfast." },
  { en: "comply", ko: "준수하다", example: "All products must comply with safety standards." },
  { en: "confirm", ko: "확인하다", example: "Please confirm your reservation by email." },
  { en: "contract", ko: "계약(서)", example: "Both parties signed the contract." },
  { en: "deadline", ko: "마감 기한", example: "The deadline for submissions is Friday." },
  { en: "delay", ko: "지연", example: "The flight had a two-hour delay." },
  { en: "deliver", ko: "배달하다", example: "The package will be delivered tomorrow." },
  { en: "department", ko: "부서", example: "She works in the accounting department." },
  { en: "distribute", ko: "배포하다, 유통하다", example: "Please distribute the handouts before the meeting." },
  { en: "efficient", ko: "효율적인", example: "The new system is more efficient." },
  { en: "eligible", ko: "자격이 있는", example: "Full-time employees are eligible for bonuses." },
  { en: "employee", ko: "직원", example: "The company has over 2,000 employees." },
  { en: "enclose", ko: "동봉하다", example: "Please find the invoice enclosed." },
  { en: "equipment", ko: "장비", example: "The lab purchased new equipment." },
  { en: "estimate", ko: "견적, 추정", example: "The contractor gave us an estimate." },
  { en: "expense", ko: "비용", example: "Travel expenses will be reimbursed." },
  { en: "expertise", ko: "전문 지식", example: "Her expertise in finance is valuable." },
  { en: "facility", ko: "시설", example: "The new facility opens in March." },
  { en: "headquarters", ko: "본사", example: "Our headquarters are located in Seoul." },
  { en: "hire", ko: "고용하다", example: "We plan to hire five new engineers." },
  { en: "implement", ko: "시행하다", example: "The company will implement a new policy." },
  { en: "inquiry", ko: "문의", example: "Thank you for your inquiry about our services." },
  { en: "inventory", ko: "재고", example: "We check the inventory every month." },
  { en: "invoice", ko: "송장, 청구서", example: "The invoice must be paid within 30 days." },
  { en: "itinerary", ko: "여행 일정표", example: "Your travel itinerary has been emailed to you." },
  { en: "launch", ko: "출시하다", example: "The company will launch a new product next month." },
  { en: "maintenance", ko: "유지 보수", example: "The elevator is closed for maintenance." },
  { en: "merger", ko: "합병", example: "The merger created the largest bank in the country." },
  { en: "negotiate", ko: "협상하다", example: "They negotiated a better price." },
  { en: "notify", ko: "통지하다", example: "Please notify us of any changes." },
  { en: "objective", ko: "목표", example: "Our main objective is to increase sales." },
  { en: "postpone", ko: "연기하다", example: "The meeting was postponed until Monday." },
  { en: "preliminary", ko: "예비의", example: "The preliminary results look promising." },
  { en: "promote", ko: "승진시키다, 홍보하다", example: "She was promoted to sales director." },
  { en: "proposal", ko: "제안(서)", example: "The board accepted the proposal." },
  { en: "purchase", ko: "구매하다", example: "You can purchase tickets online." },
  { en: "qualified", ko: "자격을 갖춘", example: "We are looking for qualified applicants." },
  { en: "receipt", ko: "영수증", example: "Please keep your receipt for returns." },
  { en: "recruit", ko: "모집하다", example: "The firm is recruiting new graduates." },
  { en: "refund", ko: "환불", example: "Customers may request a full refund." },
  { en: "reimburse", ko: "상환하다, 변제하다", example: "The company will reimburse your travel costs." },
  { en: "renovation", ko: "보수, 개조", example: "The lobby is under renovation." },
  { en: "revenue", ko: "수익", example: "Revenue increased by 10 percent last year." },
  { en: "schedule", ko: "일정", example: "The schedule has been updated." },
  { en: "shipment", ko: "배송(품)", example: "The shipment arrived on time." },
  { en: "subscription", ko: "구독", example: "Your subscription expires next month." },
  { en: "supervisor", ko: "관리자, 상사", example: "Report any problems to your supervisor." },
  { en: "survey", ko: "설문 조사", example: "Please complete the customer survey." },
  { en: "warranty", ko: "품질 보증(서)", example: "The laptop comes with a two-year warranty." },
];
